// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.hiro.hcv.bio;

import edu.hiro.hcv.bio.GenbankSequence;
import edu.hiro.hcv.bio.StrandType;
import java.util.Date;

privileged aspect GenbankSequence_Roo_JavaBean {
    
    public Integer GenbankSequence.getId() {
        return this.id;
    }
    
    public void GenbankSequence.setId(Integer id) {
        this.id = id;
    }
    
    public String GenbankSequence.getGenome() {
        return this.genome;
    }
    
    public void GenbankSequence.setGenome(String genome) {
        this.genome = genome;
    }
    
    public String GenbankSequence.getChromosome() {
        return this.chromosome;
    }
    
    public void GenbankSequence.setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }
    
    public String GenbankSequence.getFamily() {
        return this.family;
    }
    
    public void GenbankSequence.setFamily(String family) {
        this.family = family;
    }
    
    public String GenbankSequence.getTaxon() {
        return this.taxon;
    }
    
    public void GenbankSequence.setTaxon(String taxon) {
        this.taxon = taxon;
    }
    
    public String GenbankSequence.getCountry() {
        return this.country;
    }
    
    public void GenbankSequence.setCountry(String country) {
        this.country = country;
    }
    
    public String GenbankSequence.getRef() {
        return this.ref;
    }
    
    public void GenbankSequence.setRef(String ref) {
        this.ref = ref;
    }
    
    public String GenbankSequence.getSequenceset() {
        return this.sequenceset;
    }
    
    public void GenbankSequence.setSequenceset(String sequenceset) {
        this.sequenceset = sequenceset;
    }
    
    public String GenbankSequence.getSource() {
        return this.source;
    }
    
    public void GenbankSequence.setSource(String source) {
        this.source = source;
    }
    
    public String GenbankSequence.getIdentifier() {
        return this.identifier;
    }
    
    public void GenbankSequence.setIdentifier(String identifier) {
        this.identifier = identifier;
    }
    
    public boolean GenbankSequence.isVisible() {
        return this.visible;
    }
    
    public void GenbankSequence.setVisible(boolean visible) {
        this.visible = visible;
    }
    
    public String GenbankSequence.getUser_id() {
        return this.user_id;
    }
    
    public void GenbankSequence.setUser_id(String user_id) {
        this.user_id = user_id;
    }
    
    public boolean GenbankSequence.isUploaded() {
        return this.uploaded;
    }
    
    public void GenbankSequence.setUploaded(boolean uploaded) {
        this.uploaded = uploaded;
    }
    
    public String GenbankSequence.getAccession() {
        return this.accession;
    }
    
    public void GenbankSequence.setAccession(String accession) {
        this.accession = accession;
    }
    
    public Integer GenbankSequence.getGi() {
        return this.gi;
    }
    
    public void GenbankSequence.setGi(Integer gi) {
        this.gi = gi;
    }
    
    public String GenbankSequence.getDefline() {
        return this.defline;
    }
    
    public void GenbankSequence.setDefline(String defline) {
        this.defline = defline;
    }
    
    public String GenbankSequence.getVersion() {
        return this.version;
    }
    
    public void GenbankSequence.setVersion(String version) {
        this.version = version;
    }
    
    public String GenbankSequence.getUniprot() {
        return this.uniprot;
    }
    
    public void GenbankSequence.setUniprot(String uniprot) {
        this.uniprot = uniprot;
    }
    
    public String GenbankSequence.getIsolate() {
        return this.isolate;
    }
    
    public void GenbankSequence.setIsolate(String isolate) {
        this.isolate = isolate;
    }
    
    public String GenbankSequence.getIsolation_source() {
        return this.isolation_source;
    }
    
    public void GenbankSequence.setIsolation_source(String isolation_source) {
        this.isolation_source = isolation_source;
    }
    
    public Integer GenbankSequence.getMolwt() {
        return this.molwt;
    }
    
    public void GenbankSequence.setMolwt(Integer molwt) {
        this.molwt = molwt;
    }
    
    public String GenbankSequence.getSubregion() {
        return this.subregion;
    }
    
    public void GenbankSequence.setSubregion(String subregion) {
        this.subregion = subregion;
    }
    
    public String GenbankSequence.getCollection_date() {
        return this.collection_date;
    }
    
    public void GenbankSequence.setCollection_date(String collection_date) {
        this.collection_date = collection_date;
    }
    
    public String GenbankSequence.getLocus_tag() {
        return this.locus_tag;
    }
    
    public void GenbankSequence.setLocus_tag(String locus_tag) {
        this.locus_tag = locus_tag;
    }
    
    public Integer GenbankSequence.getCodon_start() {
        return this.codon_start;
    }
    
    public void GenbankSequence.setCodon_start(Integer codon_start) {
        this.codon_start = codon_start;
    }
    
    public String GenbankSequence.getTransl_table() {
        return this.transl_table;
    }
    
    public void GenbankSequence.setTransl_table(String transl_table) {
        this.transl_table = transl_table;
    }
    
    public String GenbankSequence.getMol_type() {
        return this.mol_type;
    }
    
    public void GenbankSequence.setMol_type(String mol_type) {
        this.mol_type = mol_type;
    }
    
    public String GenbankSequence.getStrain() {
        return this.strain;
    }
    
    public void GenbankSequence.setStrain(String strain) {
        this.strain = strain;
    }
    
    public String GenbankSequence.getSegment() {
        return this.segment;
    }
    
    public void GenbankSequence.setSegment(String segment) {
        this.segment = segment;
    }
    
    public String GenbankSequence.getSerotype() {
        return this.serotype;
    }
    
    public void GenbankSequence.setSerotype(String serotype) {
        this.serotype = serotype;
    }
    
    public String GenbankSequence.getSerogroup() {
        return this.serogroup;
    }
    
    public void GenbankSequence.setSerogroup(String serogroup) {
        this.serogroup = serogroup;
    }
    
    public String GenbankSequence.getSerovar() {
        return this.serovar;
    }
    
    public void GenbankSequence.setSerovar(String serovar) {
        this.serovar = serovar;
    }
    
    public String GenbankSequence.getSubtype() {
        return this.subtype;
    }
    
    public void GenbankSequence.setSubtype(String subtype) {
        this.subtype = subtype;
    }
    
    public String GenbankSequence.getHost() {
        return this.host;
    }
    
    public void GenbankSequence.setHost(String host) {
        this.host = host;
    }
    
    public String GenbankSequence.getLab_host() {
        return this.lab_host;
    }
    
    public void GenbankSequence.setLab_host(String lab_host) {
        this.lab_host = lab_host;
    }
    
    public String GenbankSequence.getSpecific_host() {
        return this.specific_host;
    }
    
    public void GenbankSequence.setSpecific_host(String specific_host) {
        this.specific_host = specific_host;
    }
    
    public String GenbankSequence.getPlasmid() {
        return this.plasmid;
    }
    
    public void GenbankSequence.setPlasmid(String plasmid) {
        this.plasmid = plasmid;
    }
    
    public String GenbankSequence.getAllele() {
        return this.allele;
    }
    
    public void GenbankSequence.setAllele(String allele) {
        this.allele = allele;
    }
    
    public String GenbankSequence.getCodedby() {
        return this.codedby;
    }
    
    public void GenbankSequence.setCodedby(String codedby) {
        this.codedby = codedby;
    }
    
    public String GenbankSequence.getProduct() {
        return this.product;
    }
    
    public void GenbankSequence.setProduct(String product) {
        this.product = product;
    }
    
    public String GenbankSequence.getOldid() {
        return this.oldid;
    }
    
    public void GenbankSequence.setOldid(String oldid) {
        this.oldid = oldid;
    }
    
    public Boolean GenbankSequence.getTruncated() {
        return this.truncated;
    }
    
    public void GenbankSequence.setTruncated(Boolean truncated) {
        this.truncated = truncated;
    }
    
    public Date GenbankSequence.getUdate() {
        return this.udate;
    }
    
    public void GenbankSequence.setUdate(Date udate) {
        this.udate = udate;
    }
    
    public String GenbankSequence.getDivision() {
        return this.division;
    }
    
    public void GenbankSequence.setDivision(String division) {
        this.division = division;
    }
    
    public String GenbankSequence.getNatype() {
        return this.natype;
    }
    
    public void GenbankSequence.setNatype(String natype) {
        this.natype = natype;
    }
    
    public Boolean GenbankSequence.getCircular() {
        return this.circular;
    }
    
    public void GenbankSequence.setCircular(Boolean circular) {
        this.circular = circular;
    }
    
    public String GenbankSequence.getClone() {
        return this.clone;
    }
    
    public void GenbankSequence.setClone(String clone) {
        this.clone = clone;
    }
    
    public String GenbankSequence.getComments() {
        return this.comments;
    }
    
    public void GenbankSequence.setComments(String comments) {
        this.comments = comments;
    }
    
    public String GenbankSequence.getNotes() {
        return this.notes;
    }
    
    public void GenbankSequence.setNotes(String notes) {
        this.notes = notes;
    }
    
    public Date GenbankSequence.getCreated() {
        return this.created;
    }
    
    public void GenbankSequence.setCreated(Date created) {
        this.created = created;
    }
    
    public Date GenbankSequence.getUpdated() {
        return this.updated;
    }
    
    public void GenbankSequence.setUpdated(Date updated) {
        this.updated = updated;
    }
    
    public String GenbankSequence.getMethod() {
        return this.method;
    }
    
    public void GenbankSequence.setMethod(String method) {
        this.method = method;
    }
    
    public String GenbankSequence.getModel() {
        return this.model;
    }
    
    public void GenbankSequence.setModel(String model) {
        this.model = model;
    }
    
    public Double GenbankSequence.getScore() {
        return this.score;
    }
    
    public void GenbankSequence.setScore(Double score) {
        this.score = score;
    }
    
    public Double GenbankSequence.getEvalue() {
        return this.evalue;
    }
    
    public void GenbankSequence.setEvalue(Double evalue) {
        this.evalue = evalue;
    }
    
    public String GenbankSequence.getHmmloc() {
        return this.hmmloc;
    }
    
    public void GenbankSequence.setHmmloc(String hmmloc) {
        this.hmmloc = hmmloc;
    }
    
    public Boolean GenbankSequence.getPseudogene() {
        return this.pseudogene;
    }
    
    public void GenbankSequence.setPseudogene(Boolean pseudogene) {
        this.pseudogene = pseudogene;
    }
    
    public Integer GenbankSequence.getStart() {
        return this.start;
    }
    
    public void GenbankSequence.setStart(Integer start) {
        this.start = start;
    }
    
    public Integer GenbankSequence.getEnd() {
        return this.end;
    }
    
    public void GenbankSequence.setEnd(Integer end) {
        this.end = end;
    }
    
    public StrandType GenbankSequence.getStrand() {
        return this.strand;
    }
    
    public void GenbankSequence.setStrand(StrandType strand) {
        this.strand = strand;
    }
    
    public Integer GenbankSequence.getNumexons() {
        return this.numexons;
    }
    
    public void GenbankSequence.setNumexons(Integer numexons) {
        this.numexons = numexons;
    }
    
    public String GenbankSequence.getLocus() {
        return this.locus;
    }
    
    public void GenbankSequence.setLocus(String locus) {
        this.locus = locus;
    }
    
    public String GenbankSequence.getGene() {
        return this.gene;
    }
    
    public void GenbankSequence.setGene(String gene) {
        this.gene = gene;
    }
    
    public Integer GenbankSequence.getGeneid() {
        return this.geneid;
    }
    
    public void GenbankSequence.setGeneid(Integer geneid) {
        this.geneid = geneid;
    }
    
    public String GenbankSequence.getProtein_id() {
        return this.protein_id;
    }
    
    public void GenbankSequence.setProtein_id(String protein_id) {
        this.protein_id = protein_id;
    }
    
    public Integer GenbankSequence.getProtein_gi() {
        return this.protein_gi;
    }
    
    public void GenbankSequence.setProtein_gi(Integer protein_gi) {
        this.protein_gi = protein_gi;
    }
    
    public String GenbankSequence.getProtein() {
        return this.protein;
    }
    
    public void GenbankSequence.setProtein(String protein) {
        this.protein = protein;
    }
    
    public String GenbankSequence.getSplicing() {
        return this.splicing;
    }
    
    public void GenbankSequence.setSplicing(String splicing) {
        this.splicing = splicing;
    }
    
    public String GenbankSequence.getSeg() {
        return this.seg;
    }
    
    public void GenbankSequence.setSeg(String seg) {
        this.seg = seg;
    }
    
    public String GenbankSequence.getDust() {
        return this.dust;
    }
    
    public void GenbankSequence.setDust(String dust) {
        this.dust = dust;
    }
    
    public Float GenbankSequence.getGc() {
        return this.gc;
    }
    
    public void GenbankSequence.setGc(Float gc) {
        this.gc = gc;
    }
    
    public Float GenbankSequence.getGc3() {
        return this.gc3;
    }
    
    public void GenbankSequence.setGc3(Float gc3) {
        this.gc3 = gc3;
    }
    
    public Float GenbankSequence.getGc3skew() {
        return this.gc3skew;
    }
    
    public void GenbankSequence.setGc3skew(Float gc3skew) {
        this.gc3skew = gc3skew;
    }
    
    public Integer GenbankSequence.getDomainnum() {
        return this.domainnum;
    }
    
    public void GenbankSequence.setDomainnum(Integer domainnum) {
        this.domainnum = domainnum;
    }
    
    public Integer GenbankSequence.getTotaldomainnum() {
        return this.totaldomainnum;
    }
    
    public void GenbankSequence.setTotaldomainnum(Integer totaldomainnum) {
        this.totaldomainnum = totaldomainnum;
    }
    
    public String GenbankSequence.getDomains() {
        return this.domains;
    }
    
    public void GenbankSequence.setDomains(String domains) {
        this.domains = domains;
    }
    
    public String GenbankSequence.getArchitecture() {
        return this.architecture;
    }
    
    public void GenbankSequence.setArchitecture(String architecture) {
        this.architecture = architecture;
    }
    
    public String GenbankSequence.getEc() {
        return this.ec;
    }
    
    public void GenbankSequence.setEc(String ec) {
        this.ec = ec;
    }
    
    public Boolean GenbankSequence.getConceptual() {
        return this.conceptual;
    }
    
    public void GenbankSequence.setConceptual(Boolean conceptual) {
        this.conceptual = conceptual;
    }
    
    public Integer GenbankSequence.getNtlength() {
        return this.ntlength;
    }
    
    public void GenbankSequence.setNtlength(Integer ntlength) {
        this.ntlength = ntlength;
    }
    
    public Integer GenbankSequence.getAalength() {
        return this.aalength;
    }
    
    public void GenbankSequence.setAalength(Integer aalength) {
        this.aalength = aalength;
    }
    
    public String GenbankSequence.getSpliced() {
        return this.spliced;
    }
    
    public void GenbankSequence.setSpliced(String spliced) {
        this.spliced = spliced;
    }
    
    public String GenbankSequence.getSequence() {
        return this.sequence;
    }
    
    public void GenbankSequence.setSequence(String sequence) {
        this.sequence = sequence;
    }
    
    public String GenbankSequence.getTranslation() {
        return this.translation;
    }
    
    public void GenbankSequence.setTranslation(String translation) {
        this.translation = translation;
    }
    
    public String GenbankSequence.getSecondary() {
        return this.secondary;
    }
    
    public void GenbankSequence.setSecondary(String secondary) {
        this.secondary = secondary;
    }
    
}
