// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.hiro.hcv.hcv;

import java.lang.String;
import java.util.List;

privileged aspect HcvGenome_Roo_JavaBean {
    
    public String HcvGenome.getAccession() {
        return this.accession;
    }
    
    public void HcvGenome.setAccession(String accession) {
        this.accession = accession;
    }
    
    public String HcvGenome.getSequence() {
        return this.sequence;
    }
    
    public void HcvGenome.setSequence(String sequence) {
        this.sequence = sequence;
    }
    
    public List<String> HcvGenome.getRefs() {
        return this.refs;
    }
    
    public void HcvGenome.setRefs(List<String> refs) {
        this.refs = refs;
    }
    
    public CDS HcvGenome.getCds() {
        return this.cds;
    }
    
    public void HcvGenome.setCds(CDS cds) {
        this.cds = cds;
    }
    
}
